#!/bin/bash

[ -z "$OBJECTSERVER_PRIMARY_HOST" ] && OBJECTSERVER_PRIMARY_HOST=$OBJSRV_PORT_4100_TCP_ADDR
[ -z "$OBJECTSERVER_PRIMARY_PORT" ] && OBJECTSERVER_PRIMARY_PORT=$OBJSRV_PORT_4100_TCP_PORT
[ -z "$OBJECTSERVER_PRIMARY_NAME" ] && OBJECTSERVER_PRIMARY_NAME=$OBJSRV_ENV_OBJSRV
[ -z "$OBJECTSERVER_USER" ] && OBJECTSERVER_USER=root

for VAR in OBJECTSERVER_PRIMARY_HOST OBJECTSERVER_PRIMARY_NAME OBJECTSERVER_USER OBJECTSERVER_PASSWORD OBJECTSERVER_ENCRYPTED OBJECTSERVER_ALGORITHM_ATTRIBUTE OBJECTSERVER_SSL OBJECTSERVER_PRIMARY_PORT OBJECTSERVER_SECONDARY_HOST OBJECTSERVER_FAILOVER OBJECTSERVER_SECONDARY_PORT
do
   echo "Setting CONFIGURATION_TOKEN_$VAR to ${!VAR}"
   sed -i"" -e "s/@CONFIGURATION_TOKEN_$VAR@/${!VAR}/g" /opt/IBM/netcool/omnibus_webgui/etc/datasources/ncwDataSourceDefinitions.xml
done

[ ! -f /usr/local/bin/startJazz.sh ] && /opt/IBM/JazzSM/profile/bin/startServer.sh server1 -script /usr/local/bin/startJazz.sh
exec /usr/local/bin/startJazz.sh
